name: Build-Linux-Executable
run-name: Building Linux Executable
on:
  push:
    tags:
      - v**

jobs:
    Build-Linux-Executable:
        runs-on: ubuntu-latest
        steps:
            
            - uses: actions/checkout@v3

            - name: Set up Maven
              uses: stCarolas/setup-maven@v4.5
              with:
                maven-version: 3.8.8

            # Installing and setting up GraalVM(gluon)
            - run: sudo apt-get update
            - run: sudo apt-get install -y wget gcc pkg-config libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libfreetype6-dev libgl-dev libglib2.0-dev libglib2.0-dev libgtk-3-dev libpango1.0-dev libx11-dev libxtst-dev zlib1g-dev libstdc++6 libc++1 libstdc++5
            - run: wget https://github.com/gluonhq/graal/releases/download/gluon-22.1.0.1-Final/graalvm-svm-java17-linux-gluon-22.1.0.1-Final.tar.gz -O graalvm.tar.gz
            - run: tar -xzf graalvm.tar.gz
            - run: echo GRAALVM_HOME="$(pwd)/graalvm-svm-java17-linux-gluon-22.1.0.1-Final" >> $GITHUB_ENV
            - run: echo JAVA_HOME="${GRAALVM_HOME}" >> $GITHUB_ENV
            
            # Building the project as a native linux app 
            - run: mvn clean gluonfx:build

            # Get project version
            - run: echo SHOWLY_DESKTOP_VERSION="$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

            # Renaming the executable to have the name and version of the project
            - run: mv target/gluonfx/x86_64-linux/desktop ./showly-desktop-${SHOWLY_DESKTOP_VERSION}
            
            # Upload linux executable to releases
            - uses: xresloader/upload-to-github-release@v1.4.2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                file: "./showly-desktop-*"
                tags: true
                draft: true